import Dashboard from "./Dashboard";
import NotFound from "./NotFound";
import GuestView from "./GuestView";
import GuestsView from "./GuestsView";
import ContactView from "./ContactView";
import ConciergeView from "./ConciergeView";
import NewUser from "./NewUser";
import NewRoom from "./NewRoom";
import NewBooking from "./NewBooking";

export { Dashboard };
export { NotFound };
export { GuestView };
export { GuestsView };
export { ConciergeView };
export { ContactView };
export { NewUser };
export { NewRoom };
export { NewBooking };
