export interface IBooking  {
   _id: string,
   photo: string,
   guest_name: string,
   order_date: string,
   check_in: string,
   check_out: string,
   request: string,
   room_type: string,
   status: string,
   price: string,
   amenities: string,
   room_desc: string, 
	room_id: string,
	user_id: string,
	room_images?: string[],
}